#!/usr/bin/env python3 
# Fibonacci series:
# the sum of two elements defines the next

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# return list with fibonacci numbers up to n
def fiboEvenSum(r):
    result = 0
    a, b = 0, 1
    while a < r+1:
        if a % 2 == 0:
            result += a 
        a, b = b, a+b
    return result

# wenn als script aufgerufen
if __name__ == '__main__':
    print(fiboEvenSum(4000000))